#								__							_
#								\ \			 ___ __| |_
#								 > >		|_ /(_-< ' \
#								/_/			/__|___/_||_|			___
#																				 |___|

#				* auther		: k0k1
#				* ver				: 0.12

export ZDOTDIR=$HOME/.zsh
