#								__							_
#								\ \			 ___ __| |_
#								 > >		|_ /(_-< ' \
#								/_/			/__|___/_||_|			___
#																				 |___|

#				* auther		: kip-s
#				* url				: https://kip-s.net
#				* ver				: 0.11

export ZDOTDIR=$HOME/.zsh
